language: php
branches:
  only:
    - v6
php:
  - 5.6
  - 7.0
  - 7.1
services:
  - mysql
  - redis-server
  - elasticsearch
before_install:
  - sudo apt-get update
  #DEPLOY KEY
  #SEE: https://gist.github.com/cblanquera/3ff60b4c9afc92be1ac0a9d57afceb17#file-instructions-md
  - openssl aes-256-cbc -K $encrypted_7cad948dbd62_key -iv $encrypted_7cad948dbd62_iv
    -in travis_rsa.enc -out /tmp/travis_rsa -d
  - chmod 600 /tmp/travis_rsa
install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
sudo: required
before_script:
  #MYSQL 5.7
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  #CONFIG
  - cp config/settings.sample.php config/settings.php
  - cp config/test.sample.php config/test.php
  - cp config/test.sample.php config/services.php
  - cp config/deploy.sample.php config/deploy.php
  - composer self-update
  - composer install
  #PHP SERVER
  - php -S 127.0.0.1:8888 -t ./public >/dev/null 2>&1 &
  #PHANTOM
  - bin/phantomjs --webdriver=4444 >/dev/null 2>&1 &
script:
  - bin/codecept run unit -c ./app/core
  - bin/codecept run -c ./app/www
#deploy:
#  provider: script
#  script: "./bin/cradle app/core deploy-production;./bin/cradle app/core deploy-cdn"
#  on:
#    branch: v6
notifications:
  slack: openovate:Kz0BdrOZJmiy6BAoGKsNmcnv
